name: Run Python Script Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"   # Runs every 5 minutes
  workflow_dispatch:        # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python main.py
